default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: calendar_app_development

test:
  <<: *default
  database: calendar_app_test

production:
  <<: *default
  database: calendar_app_production
  username: calendar_app
  password: <%= ENV['CALENDAR_APP_DATABASE_PASSWORD'] %>
