# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77e39e8a210dad709818d9b9645bdbd674abda1f5e89aabaff54cb403d161feb2f3ee93adef32665246ba074eceba3d23f80df0c2d11d2d9116dd94e65469e1a

test:
  secret_key_base: cd4dcd1f7195f8b1765e6940788dc9b8f0e542f92d3b32a90a87d24e56714c644a0018d86ba405a6af2b13b3121d6eaf03271665e724b77f8842928715733584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
